### PR TITLE
Implement check-in scan, custom QR upload, and displaying event QR Code

### PR DESCRIPTION
**Pull request by dpardell**
A somewhat big PR that ties together some key components of our app. 

- Creating an event now also creates a corresponding QR Code
- Event QR codes can now be viewed by selecting an event as an organizer.
- Upon creating an event, as custom code can be scanned in and used in place of an auto generated one.
- Scanning such a code as an attendee will check you into the event.

### CODE REVIEW

**Review by adrienz1 — APPROVED** [review]
looks good

**Review by Aryan-Rusia-2 — APPROVED** [review]
Looks good to me!

**Review by LyndenJ — APPROVED** [review]
Good stuff David

**Comment by dpardell** [comment]
> There was a conflict in the Attendee Main Activity after I merged my recent PR into the main branch. I've resolved the issue, but just to be sure, please take a look at it as well.

Took a look and looks good. Thanks for handling this.

**Pull request merged**
